Serial Rx and Telemetry Pin Swap configuration support
rotorflight/rotorflight-configurator pull request #123
Opened 2024-08-09 13:57 UTC by Oats87

Add support for setting Pin swap for serialrx and telemetry on the receiver page

(vtx is not supported via configurator, and esc_sensor_config currently via configurator only allows setting protocol, leaving this to be CLI-only for now)

To support: https://github.com/rotorflight/rotorflight-firmware/commit/240a40e6167455e7d6ea3bfe6c728439696f1c92

<img width="1840" alt="Screenshot 2024-08-09 at 9 53 38 AM" src="https://github.com/user-attachments/assets/bee9c61f-68b6-4867-bea4-a9c5f6e9cbd8">

2024-08-15 13:33 UTC, rotorflight requested changes
Please explain / fix the updateButton() call

2024-08-15 13:33 UTC, rotorflight commented on src/js/fc.js
> +            pinswap:                    0,
This is already defined

2024-08-15 13:33 UTC, rotorflight commented on src/js/fc.js
> +            serialrx_pinswap:             0,
This is defined

2024-08-15 13:33 UTC, rotorflight commented on src/js/fc.js
> +            telemetry_pinswap:              0,
This is defined

2024-08-15 13:33 UTC, rotorflight commented on src/js/tabs/receiver.js
> +                updateButtons(true);
Why are you calling updateButtons here?

2024-08-15 17:44 UTC, Oats87 commented on src/js/tabs/receiver.js
> +                updateButtons(true);
`updateButtons` seems to trigger the bottom bar (save/reboot/etc.) to appear if the value is changed. this is copied logic from the serialRx side.

2024-08-15 18:11 UTC, Oats87 commented on src/js/tabs/receiver.js
> +                updateButtons(true);
ok, seems the `.content_wrapper` change definition drives the updateButtons so I've gone ahead and removed them.

2024-08-16 11:14 UTC, rotorflight approved these changes

2024-08-16 11:14 UTC, merged