Add a checkbox to show all ports if desired
rotorflight/rotorflight-configurator pull request #152
Opened 2024-09-11 00:22 UTC by Oats87

Add a checkbox to show all ports if desired 
<img width="612" alt="Screenshot 2024-09-10 at 5 19 48 PM" src="https://github.com/user-attachments/assets/c1303377-863e-4d65-a94f-9d1657ee525b">

<img width="433" alt="Screenshot 2024-09-10 at 5 19 57 PM" src="https://github.com/user-attachments/assets/1f20bfc1-a867-478f-98e7-2e7c0eb0ba06">

<img width="433" alt="Screenshot 2024-09-10 at 5 20 02 PM" src="https://github.com/user-attachments/assets/09b1216e-2712-4f6e-b956-b57db5b84bf4">

2024-09-20 00:59 UTC, breavyn requested changes

2024-09-20 00:59 UTC, breavyn commented on src/js/serial.js
This is leaking the GUI into the serial driver. Move the filter out into the port handler, either at the call site or perhaps in `updatePortSelect`.

2024-09-23 20:27 UTC, Oats87 commented
@breavyn I went ahead and moved the filter out (and am now just calling `.filter` on the array). 

I think we still need to figure out what to do about Android. We could hide the element and default it to "show all ports" if running on android (but I don't know how to reliably determine this) or something else...

2024-09-24 01:39 UTC, breavyn requested changes
When enabling show all, this is autoconnecting to a device if available. I don't think this is the correct behaviour.

For android, I think it will be best to ignore `show_all_ports` and hide the toggle widget for now. We can revisit this in the future when device names are working.

2024-09-24 01:39 UTC, breavyn commented on src/js/port_handler.js
> -            const isWindows = (OS === 'Windows');
`OS` is now unused, remove it.

2024-09-24 01:39 UTC, breavyn commented on src/js/port_handler.js
Fix the lint errors in this file. You can see them with  `yarn lint`.

2024-09-24 17:55 UTC, Oats87 commented on src/js/port_handler.js
File has been corrected to pass `yarn lint`

2024-09-24 17:55 UTC, Oats87 commented on src/js/port_handler.js
> -            const isWindows = (OS === 'Windows');
Removed `OS`

2024-09-25 01:30 UTC, breavyn requested changes
This is looking good. I've tested it behaves as expected on desktop and android.

Fix the `currentPorts` assignment and I'll approve. Also don't be afraid to split long comments into multiple lines.

2024-09-25 01:30 UTC, breavyn commented on src/js/port_handler.js
> +            currentPorts = currentPorts = currentPorts.filter((p) => portRecognized(p.displayName, p.path));
Reassign `currentPorts` once.

2024-09-25 01:36 UTC, Oats87 commented on src/js/port_handler.js
> +            currentPorts = currentPorts = currentPorts.filter((p) => portRecognized(p.displayName, p.path));
oops

2024-09-25 01:40 UTC, breavyn approved these changes

2024-09-28 09:54 UTC, rotorflight approved these changes

2024-09-28 09:55 UTC, merged