Update nouislider
rotorflight/rotorflight-configurator pull request #163
Opened 2024-09-23 02:32 UTC by breavyn

This fixes the issue of the slider handles sticking to the cursor after interaction has finished.

nouislider no longer uses jquery, so there are some code changes to integrate it.

2024-09-23 22:02 UTC, rburrow87 commented
This is with Ubuntu 24.10 using the deb artifact.

Mixer:
- If I enable override and set some value, when I switch to another tab and come back, it moves the slider back to 0 instead of the current value.

Adjustments:
- If I change from `Off` to `Mapped` and then set it to `Rate Profile Selection`, the slider to adjust the selection range cannot be dragged around. If I go to another tab and come back, it works as expected. Applies to `Profile Selection` and probably others too.

- The `Enable Channel` slider moves when you double click it when set to `ALWAYS`, and even if the adjustment is off entirely.

2024-09-24 03:02 UTC, rburrow87 commented
Those issues seem fixed to me! Checked in a Windows 11 VM and Ubuntu again.

However, I just realized motor override does NOT turn off anymore when you try to toggle it off and you have an override >0% set. I tried the last master branch CI build (ed1e978) and it works fine there, so I'm wondering if that's related to something in this PR?

2024-09-28 13:42 UTC, rotorflight commented on src/css/tabs/adjustments.css
>      height: 6px;
Looks like a duplicate?

2024-09-28 13:44 UTC, rotorflight requested changes
Check the possible dup

2024-09-28 23:11 UTC, rotorflight approved these changes

2024-09-28 23:13 UTC, merged